### ISSUE TITLE
Seems to require PostgreSQL >= 11

### ISSUE THREAD

**Issue by Natureshadow** [tvondra/tdigest#11]
It seems that this extension requires PostgreSQL >= 11 because it uses the `pg_sendint32` function, which is unavailable in odler versions.

If this is correct and intended, I suggest adding a note to the readme.

**Comment by tvondra** [comment]
No, that's not intentional. I've pushed 2548a52f5b6c6ff9093ac6911c076784eea09e1f fixing this, and it'll be included in the next release.
