### ISSUE TITLE
Handle null input

### ISSUE THREAD

**Issue by rahulbsw** [tvondra/tdigest#13]
providing handling to null input value , while doing aggregation

**Comment by tvondra** [comment]
I'm confused - what change do you propose / request? Please, elaborate.

**Comment by tvondra** [comment]
I've spent some time today experimenting with aggregation and NULL values, and I still can't say what this report is about. Baed on that, I'm going to close it - if you still think there's an issue (and there very well may be), please file a more detailed report. Ideally with an example that does not work the way you want it to work.
