### ISSUE TITLE
tdigest segfaults with PG10 on amd64

### ISSUE THREAD

**Issue by df7cb** [tvondra/tdigest#22]
tdigest segfaults with PG10 on amd64 (x86_64):
https://github.com/df7cb/tdigest/runs/4719521616?check_suite_focus=true

**Comment by tvondra** [comment]
Thanks for the report - indeed, the PG10 seems to work differently when combining results of partial aggregates. Should be fixed by 745b58ddc2d7b282a93193162c1a5c69a476e361.
